[com.mitchellh.ghostty]
leftmeta.c = C-S-c
leftmeta.v = C-S-v
leftmeta.t = C-S-t

[firefox*]
leftmeta.r = C-r

[librewolf*]
leftmeta.r = C-r

[zen*]
leftmeta.r = C-r

[floorp*]
leftmeta.r = C-r

[chromium*]
leftmeta.r = C-r

[*chrome*]
leftmeta.r = C-r

[brave*]
leftmeta.r = C-r

[vivaldi*]
leftmeta.r = C-r

[opera*]
leftmeta.r = C-r

[*edge*]
leftmeta.r = C-r
