[com.mitchellh.ghostty]
meta+c = C-S-c
meta+v = C-S-v
meta+t = C-S-t

[firefox*]
meta+r = C-r

[librewolf*]
meta+r = C-r

[zen*]
meta+r = C-r

[floorp*]
meta+r = C-r

[chromium*]
meta+r = C-r

[*chrome*]
meta+r = C-r

[brave*]
meta+r = C-r

[vivaldi*]
meta+r = C-r

[opera*]
meta+r = C-r

[*edge*]
meta+r = C-r
